language: node_js
node_js:
  - node
  - 8
before_install:
  - npm config set depth 0
notifications:
  email: false
sudo: false
script:
  - npm run test
  - npm run lint
after_success:
  - semantic-release pre && npm publish && semantic-release post
